<?php

declare(strict_types=1);

/*
 * SiskomVoiceAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SiskomVoiceAPILib\Tests\Controllers;

use Core\TestCase\BodyMatchers\KeysBodyMatcher;
use Core\TestCase\TestParam;
use SiskomVoiceAPILib\Controllers\CallController;
use SiskomVoiceAPILib\Exceptions;
use SiskomVoiceAPILib\Models;

class CallControllerTest extends BaseTestController
{
    /**
     * @var CallController CallController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getCallController();
    }

    public function testBlast()
    {
        // Parameters for the API call
        $body = TestParam::object(
            "{\r\n  \"callerid\": \"6285757920463\",\r\n  \"destination\": \"6285772337980\",\r" .
            "\n  \"text_to_speech\": \"Halo mas machri apa kabar? halo mas machri apa\",\r\n  \"" .
            "language\": \"id_ID\",\r\n  \"gender\": \"FEMALE\",\r\n  \"repeat\": 10,\r\n  \"ext" .
            "ernal_id\": \"[EXTERNAL_ID]\",\r\n  \"callback_url\": \"https://eov2zjk1xwqtjan.m.p" .
            "ipedream.net\"\r\n}",
            Models\Blastrequest::class
        );

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->blast($body);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json; charset=utf-8', false];
        $headers['Date'] = ['Thu, 15 Sep 2022 20:54:39 GMT', false];
        $headers['Server'] = ['Apache/2.4.41 (Ubuntu)', false];
        $headers['X-Powered-By'] = ['Express', false];
        $headers['Content-Length'] = ['388', false];
        $headers['ETag'] = ['W/"184-elA/SmcpetDscC+SvlMrTEtDfhU"', false];
        $headers['Keep-Alive'] = ['timeout=5, max=100', false];
        $headers['Connection'] = ['Keep-Alive', false];

        // Assert result with expected response
        $this->newTestCase($result)
        ->expectStatus(200)
        ->allowExtraHeaders()
        ->expectHeaders($headers)
        ->bodyMatcher(KeysBodyMatcher::init(
            TestParam::object(
                "{\r\n  \"response\": true,\r\n  \"rcode\": {\r\n    \"transaction_id\": \"489E" .
                "F4175D9E35DDAEFD74839DB9558D\",\r\n    \"callback_key\": \"25c1e6ec24db6cf8bcff" .
                "665761e1c985\",\r\n    \"destination\": \"62127867676\",\r\n    \"text_to_speec" .
                "h\": \"Hai.... Selamat datang saudara-saudaraku, anda adalah pelanggan utama ha" .
                "ri ini, selamat yaaa gaeees!\",\r\n    \"language\": \"id-ID\",\r\n    \"gender" .
                "\": \"FEMALE\",\r\n    \"VoiceRepeat\": \"2\",\r\n    \"external_id\": \"938948" .
                "93483984938\",\r\n    \"callback_url\": \"http\"\r\n  }\r\n}"
            ),
            false,
            false
        ))
        ->assert();
    }
}
