<?php

declare(strict_types=1);

/*
 * SiskomVoiceAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SiskomVoiceAPILib\Tests\Controllers;

use Core\TestCase\BodyMatchers\KeysBodyMatcher;
use Core\TestCase\BodyMatchers\RawBodyMatcher;
use Core\TestCase\TestParam;
use SiskomVoiceAPILib\Controllers\IVRController;
use SiskomVoiceAPILib\Exceptions;

class IVRControllerTest extends BaseTestController
{
    /**
     * @var IVRController IVRController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getIVRController();
    }

    public function testIVRList()
    {

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->iVRList();
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json; charset=utf-8', false];
        $headers['Date'] = ['Thu, 15 Sep 2022 20:46:22 GMT', false];
        $headers['Server'] = ['Apache/2.4.41 (Ubuntu)', false];
        $headers['X-Powered-By'] = ['Express', false];
        $headers['Content-Length'] = ['4519', false];
        $headers['ETag'] = ['W/"11a7-pLkSoPsI0Gz6z88yEXkPHOuVhTA"', false];
        $headers['Keep-Alive'] = ['timeout=5, max=100', false];
        $headers['Connection'] = ['Keep-Alive', false];

        // Assert result with expected response
        $this->newTestCase($result)
        ->expectStatus(200)
        ->allowExtraHeaders()
        ->expectHeaders($headers)
        ->bodyMatcher(RawBodyMatcher::init(
            "{\n    \"response\": true,\n    \"data\": [\n        {\n            \"id\": 36,\n " .
            "           \"customer_code\": \"GOJEK\",\n            \"ivr_name\": \"TOKO_BUAH\"," .
            "\n            \"ivr_title\": \"MAIN_IVR\",\n            \"ivr_parent\": 0,\n       " .
            "     \"ivr_text\": \"Selamat datang di toko buah, disini anda akan mendapatkan buah" .
            " terbaik, untuk pembelian buah, tekan 1, untuk pembelian bibit buah, tekan 2, untuk" .
            " pembelian pupuk buah, tekan 3, tekan 4 untuk menghubungi layanan pelanggan, tekan " .
            "5 untuk apa, tekan angka 9 untuk mengakhiri\",\n            \"language\": \"id-ID\"" .
            ",\n            \"gender\": \"MALE\",\n            \"key_pressed\": 0,\n            " .
            "\"exit_key\": \"9\",\n            \"back_menu\": 8,\n            \"main_menu\": \"0" .
            "\",\n            \"action\": \"MAIN\",\n            \"action_detail\": \"\",\n     " .
            "       \"trying\": 3,\n            \"isActive\": 1,\n            \"children\": [\n " .
            "               {\n                    \"id\": 37,\n                    \"customer_c" .
            "ode\": \"GOJEK\",\n                    \"ivr_name\": \"TOKO_BUAH\",\n              " .
            "      \"ivr_title\": \"BUAH\",\n                    \"ivr_parent\": 36,\n          " .
            "          \"ivr_text\": \"Untuk membeli buah mangga tekan1, untuk membeli buah jeru" .
            "k tekan 2, untuk membeli buah salak tekan 3, untuk mengakhiri tekan angka 9\",\n   " .
            "                 \"language\": \"id-ID\",\n                    \"gender\": \"MALE\"" .
            ",\n                    \"key_pressed\": 1,\n                    \"exit_key\": \"9\"" .
            ",\n                    \"back_menu\": 8,\n                    \"main_menu\": \"0\"," .
            "\n                    \"action\": \"NONE\",\n                    \"action_detail\":" .
            " \"\",\n                    \"trying\": 3,\n                    \"isActive\": 1,\n " .
            "                   \"children\": [\n                        {\n                    " .
            "        \"id\": 42,\n                            \"customer_code\": \"GOJEK\",\n   " .
            "                         \"ivr_name\": \"TOKO_BUAH\",\n                            " .
            "\"ivr_title\": \"BUAH JERUK\",\n                            \"ivr_parent\": 37,\n  " .
            "                          \"ivr_text\": \"Untuk jeruk bali tekan 1, jeruk yang lain" .
            " tekan 2, tekan 3 untuk mengakhiri\",\n                            \"language\": \"" .
            "id-ID\",\n                            \"gender\": \"MALE\",\n                      " .
            "      \"key_pressed\": 1,\n                            \"exit_key\": \"9\",\n      " .
            "                      \"back_menu\": 8,\n                            \"main_menu\":" .
            " \"0\",\n                            \"action\": \"none\",\n                       " .
            "     \"action_detail\": \"\",\n                            \"trying\": 3,\n        " .
            "                    \"isActive\": 1\n                        },\n                  " .
            "      {\n                            \"id\": 69,\n                            \"cus" .
            "tomer_code\": \"GOJEK\",\n                            \"ivr_name\": \"TOKO_BUAH\"," .
            "\n                            \"ivr_title\": \"Mangga\",\n                         " .
            "   \"ivr_parent\": 37,\n                            \"ivr_text\": \"Mangga sedang h" .
            "abis\",\n                            \"language\": \"id-ID\",\n                    " .
            "        \"gender\": \"MALE\",\n                            \"key_pressed\": 2,\n   " .
            "                         \"exit_key\": \"9\",\n                            \"back_m" .
            "enu\": 8,\n                            \"main_menu\": \"0\",\n                     " .
            "       \"action\": \"none\",\n                            \"action_detail\": null," .
            "\n                            \"trying\": 3,\n                            \"isActiv" .
            "e\": 1\n                        }\n                    ]\n                },\n     " .
            "           {\n                    \"id\": 38,\n                    \"customer_code" .
            "\": \"GOJEK\",\n                    \"ivr_name\": \"TOKO_BUAH\",\n                 " .
            "   \"ivr_title\": \"BIBIT\",\n                    \"ivr_parent\": 36,\n            " .
            "        \"ivr_text\": \"Untuk bibit lokal tekan 1, untuk bibit import tekan 2, untu" .
            "k mengakhiri tekan 9\",\n                    \"language\": \"id-ID\",\n            " .
            "        \"gender\": \"MALE\",\n                    \"key_pressed\": 2,\n           " .
            "         \"exit_key\": \"9\",\n                    \"back_menu\": 8,\n             " .
            "       \"main_menu\": \"0\",\n                    \"action\": \"MON\",\n           " .
            "         \"action_detail\": \"\",\n                    \"trying\": 3,\n            " .
            "        \"isActive\": 1,\n                    \"children\": [\n                    " .
            "    {\n                            \"id\": 43,\n                            \"custo" .
            "mer_code\": \"GOJEK\",\n                            \"ivr_name\": \"TOKO_BUAH\",\n " .
            "                           \"ivr_title\": \"BIBIT_LOCA\",\n                        " .
            "    \"ivr_parent\": 38,\n                            \"ivr_text\": \"Bibit buah lok" .
            "al jumbo tekan 1, Bibit buah lokal biasa tekan 2\",\n                            \"" .
            "language\": \"id-ID\",\n                            \"gender\": \"FEMALE\",\n      " .
            "                      \"key_pressed\": 1,\n                            \"exit_key\"" .
            ": \"9\",\n                            \"back_menu\": 8,\n                          " .
            "  \"main_menu\": \"0\",\n                            \"action\": \"MON\",\n        " .
            "                    \"action_detail\": \"\",\n                            \"trying" .
            "\": 3,\n                            \"isActive\": 1,\n                            " .
            "\"children\": [\n                                {\n                               " .
            "     \"id\": 44,\n                                    \"customer_code\": \"GOJEK\"," .
            "\n                                    \"ivr_name\": \"TOKO_BUAH\",\n               " .
            "                     \"ivr_title\": \"BIBIT_JUMB\",\n                              " .
            "      \"ivr_parent\": 43,\n                                    \"ivr_text\": \"Untu" .
            "k bibit buah jumbo super tekan 1, bibit jumbo biasa tekan 2\",\n                   " .
            "                 \"language\": \"id-ID\",\n                                    \"ge" .
            "nder\": \"MALE\",\n                                    \"key_pressed\": 1,\n       " .
            "                             \"exit_key\": \"9\",\n                                " .
            "    \"back_menu\": 8,\n                                    \"main_menu\": \"0\",\n " .
            "                                   \"action\": \"GONE\",\n                         " .
            "           \"action_detail\": \"\",\n                                    \"trying\"" .
            ": 3,\n                                    \"isActive\": 1\n                        " .
            "        },\n                                {\n                                    " .
            "\"id\": 45,\n                                    \"customer_code\": \"GOJEK\",\n   " .
            "                                 \"ivr_name\": \"TOKO_BUAH\",\n                    " .
            "                \"ivr_title\": \"LOCAL_BIAS\",\n                                   " .
            " \"ivr_parent\": 43,\n                                    \"ivr_text\": \"Bibit bua" .
            "h local biasa hanya bisa di tanam dimusin hujan, saat ini tidak musim hujan, terima" .
            " kasih\",\n                                    \"language\": \"id-ID\",\n          " .
            "                          \"gender\": \"MALE\",\n                                  " .
            "  \"key_pressed\": 2,\n                                    \"exit_key\": \"9\",\n  " .
            "                                  \"back_menu\": 8,\n                              " .
            "      \"main_menu\": \"0\",\n                                    \"action\": \"NON" .
            "\",\n                                    \"action_detail\": \"\",\n                " .
            "                    \"trying\": 3,\n                                    \"isActive" .
            "\": 1\n                                }\n                            ]\n          " .
            "              }\n                    ]\n                },\n                {\n    " .
            "                \"id\": 39,\n                    \"customer_code\": \"GOJEK\",\n   " .
            "                 \"ivr_name\": \"TOKO_BUAH\",\n                    \"ivr_title\": " .
            "\"PUPUK\",\n                    \"ivr_parent\": 36,\n                    \"ivr_text" .
            "\": \"Untuk pembelian pupk organik tekan 1, pupuk kandang tekan 2, menghubungi laya" .
            "nan pelanggan tekan 3\",\n                    \"language\": \"id-ID\",\n           " .
            "         \"gender\": \"MALE\",\n                    \"key_pressed\": 3,\n          " .
            "          \"exit_key\": \"9\",\n                    \"back_menu\": 8,\n            " .
            "        \"main_menu\": \"0\",\n                    \"action\": \"NON\",\n          " .
            "          \"action_detail\": \"\",\n                    \"trying\": 3,\n           " .
            "         \"isActive\": 1,\n                    \"children\": [\n                   " .
            "     {\n                            \"id\": 40,\n                            \"cust" .
            "omer_code\": \"GOJEK\",\n                            \"ivr_name\": \"TOKO_BUAH\",\n" .
            "                            \"ivr_title\": \"PPK_KANDAN\",\n                       " .
            "     \"ivr_parent\": 39,\n                            \"ivr_text\": \"Pupuk kandang" .
            " sedang habis\",\n                            \"language\": \"id-ID\",\n           " .
            "                 \"gender\": \"MALE\",\n                            \"key_pressed\"" .
            ": 1,\n                            \"exit_key\": \"9\",\n                           " .
            " \"back_menu\": 8,\n                            \"main_menu\": \"0\",\n            " .
            "                \"action\": \"NO\",\n                            \"action_detail\":" .
            " \"\",\n                            \"trying\": 3,\n                            \"i" .
            "sActive\": 1\n                        },\n                        {\n              " .
            "              \"id\": 41,\n                            \"customer_code\": \"GOJEK\"" .
            ",\n                            \"ivr_name\": \"TOKO_BUAH\",\n                      " .
            "      \"ivr_title\": \"PPK_ORG\",\n                            \"ivr_parent\": 39," .
            "\n                            \"ivr_text\": \"Pupuk organik yang ada tinggal 1\",\n" .
            "                            \"language\": \"id-ID\",\n                            " .
            "\"gender\": \"FEMALE\",\n                            \"key_pressed\": 2,\n         " .
            "                   \"exit_key\": \"9\",\n                            \"back_menu\":" .
            " 8,\n                            \"main_menu\": \"0\",\n                           " .
            " \"action\": \"NO\",\n                            \"action_detail\": \"\",\n       " .
            "                     \"trying\": 3,\n                            \"isActive\": 1\n " .
            "                       }\n                    ]\n                },\n              " .
            "  {\n                    \"id\": 46,\n                    \"customer_code\": \"GOJE" .
            "K\",\n                    \"ivr_name\": \"TOKO_BUAH\",\n                    \"ivr_t" .
            "itle\": \"CS\",\n                    \"ivr_parent\": 36,\n                    \"ivr" .
            "_text\": \"Anda akan dihubungkan dengan layanan pelanggan\",\n                    " .
            "\"language\": \"id-ID\",\n                    \"gender\": \"MALE\",\n              " .
            "      \"key_pressed\": 4,\n                    \"exit_key\": \"9\",\n              " .
            "      \"back_menu\": 8,\n                    \"main_menu\": \"0\",\n               " .
            "     \"action\": \"CS\",\n                    \"action_detail\": \"\",\n           " .
            "         \"trying\": 3,\n                    \"isActive\": 1\n                },\n " .
            "               {\n                    \"id\": 75,\n                    \"customer_c" .
            "ode\": \"GOJEK\",\n                    \"ivr_name\": \"TOKO_BUAH\",\n              " .
            "      \"ivr_title\": \"apa mau\",\n                    \"ivr_parent\": 36,\n       " .
            "             \"ivr_text\": \"mau apa?\",\n                    \"language\": \"id-ID" .
            "\",\n                    \"gender\": \"MALE\",\n                    \"key_pressed\"" .
            ": 5,\n                    \"exit_key\": \"9\",\n                    \"back_menu\": " .
            "8,\n                    \"main_menu\": \"0\",\n                    \"action\": \"no" .
            "ne\",\n                    \"action_detail\": null,\n                    \"trying\"" .
            ": 3,\n                    \"isActive\": 1\n                }\n            ]\n      " .
            "  }\n    ]\n"
        ))
        ->assert();
    }

    public function testIVRLang()
    {

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->iVRLang();
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json; charset=utf-8', false];
        $headers['Date'] = ['Thu, 15 Sep 2022 20:46:31 GMT', false];
        $headers['Server'] = ['Apache/2.4.41 (Ubuntu)', false];
        $headers['X-Powered-By'] = ['Express', false];
        $headers['Content-Length'] = ['28329', false];
        $headers['ETag'] = ['W/"6ea9-PBdyBthlgN8e4f6b30cr4euL3SA"', false];
        $headers['Keep-Alive'] = ['timeout=5, max=100', false];
        $headers['Connection'] = ['Keep-Alive', false];

        // Assert result with expected response
        $this->newTestCase($result)
        ->expectStatus(200)
        ->allowExtraHeaders()
        ->expectHeaders($headers)
        ->bodyMatcher(KeysBodyMatcher::init(
            TestParam::object(
                "{\r\n  \"response\": true,\r\n  \"data\": [\r\n    {\r\n      \"code\": \"fil-" .
                "PH\",\r\n      \"name\": \"fil-PH-Wavenet-B\",\r\n      \"language\": \"Filipin" .
                "o (Philippines)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      " .
                "\"code\": \"fil-PH\",\r\n      \"name\": \"fil-PH-Wavenet-C\",\r\n      \"langu" .
                "age\": \"Filipino (Philippines)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n " .
                "   {\r\n      \"code\": \"fil-PH\",\r\n      \"name\": \"fil-PH-Wavenet-D\",\r" .
                "\n      \"language\": \"Filipino (Philippines)\",\r\n      \"gender\": \"MALE\"" .
                "\r\n    },\r\n    {\r\n      \"code\": \"fi-FI\",\r\n      \"name\": \"fi-FI-St" .
                "andard-A\",\r\n      \"language\": \"Finnish (Finland)\",\r\n      \"gender\": " .
                "\"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"fi-FI\",\r\n      \"name\": " .
                "\"fi-FI-Wavenet-A\",\r\n      \"language\": \"Finnish (Finland)\",\r\n      \"g" .
                "ender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"fr-CA\",\r\n      " .
                "\"name\": \"fr-CA-Standard-A\",\r\n      \"language\": \"French (Canada)\",\r\n" .
                "      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"fr-CA\",\r" .
                "\n      \"name\": \"fr-CA-Standard-B\",\r\n      \"language\": \"French (Canada" .
                ")\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"fr-C" .
                "A\",\r\n      \"name\": \"fr-CA-Standard-C\",\r\n      \"language\": \"French (" .
                "Canada)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\"" .
                ": \"fr-CA\",\r\n      \"name\": \"fr-CA-Standard-D\",\r\n      \"language\": \"" .
                "French (Canada)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"" .
                "code\": \"fr-CA\",\r\n      \"name\": \"fr-CA-Wavenet-A\",\r\n      \"language" .
                "\": \"French (Canada)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n" .
                "      \"code\": \"fr-CA\",\r\n      \"name\": \"fr-CA-Wavenet-B\",\r\n      \"l" .
                "anguage\": \"French (Canada)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    " .
                "{\r\n      \"code\": \"fr-CA\",\r\n      \"name\": \"fr-CA-Wavenet-C\",\r\n    " .
                "  \"language\": \"French (Canada)\",\r\n      \"gender\": \"FEMALE\"\r\n    }," .
                "\r\n    {\r\n      \"code\": \"sv-SE\",\r\n      \"name\": \"sv-SE-Wavenet-A\"," .
                "\r\n      \"language\": \"Swedish (Sweden)\",\r\n      \"gender\": \"FEMALE\"\r" .
                "\n    },\r\n    {\r\n      \"code\": \"af-ZA\",\r\n      \"name\": \"af-ZA-Stan" .
                "dard-A\",\r\n      \"language\": \"Afrikaans (South Africa)\",\r\n      \"gende" .
                "r\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"fr-CA\",\r\n      \"nam" .
                "e\": \"fr-CA-Wavenet-D\",\r\n      \"language\": \"French (Canada)\",\r\n      " .
                "\"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"sv-SE\",\r\n      " .
                "\"name\": \"sv-SE-Wavenet-B\",\r\n      \"language\": \"Swedish (Sweden)\",\r\n" .
                "      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"fr-FR\",\r" .
                "\n      \"name\": \"fr-FR-Standard-A\",\r\n      \"language\": \"French (France" .
                ")\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"ar" .
                "-XA\",\r\n      \"name\": \"ar-XA-Standard-A\",\r\n      \"language\": \"Arabic" .
                "\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"fr-" .
                "FR\",\r\n      \"name\": \"fr-FR-Standard-B\",\r\n      \"language\": \"French " .
                "(France)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\":" .
                " \"sv-SE\",\r\n      \"name\": \"sv-SE-Wavenet-C\",\r\n      \"language\": \"Sw" .
                "edish (Sweden)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"c" .
                "ode\": \"ar-XA\",\r\n      \"name\": \"ar-XA-Standard-B\",\r\n      \"language" .
                "\": \"Arabic\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"cod" .
                "e\": \"fr-FR\",\r\n      \"name\": \"fr-FR-Standard-C\",\r\n      \"language\":" .
                " \"French (France)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n   " .
                "   \"code\": \"sv-SE\",\r\n      \"name\": \"sv-SE-Wavenet-D\",\r\n      \"lang" .
                "uage\": \"Swedish (Sweden)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    " .
                "{\r\n      \"code\": \"fr-FR\",\r\n      \"name\": \"fr-FR-Standard-D\",\r\n   " .
                "   \"language\": \"French (France)\",\r\n      \"gender\": \"MALE\"\r\n    },\r" .
                "\n    {\r\n      \"code\": \"ar-XA\",\r\n      \"name\": \"ar-XA-Standard-C\"," .
                "\r\n      \"language\": \"Arabic\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n" .
                "    {\r\n      \"code\": \"fr-FR\",\r\n      \"name\": \"fr-FR-Standard-E\",\r" .
                "\n      \"language\": \"French (France)\",\r\n      \"gender\": \"FEMALE\"\r\n " .
                "   },\r\n    {\r\n      \"code\": \"sv-SE\",\r\n      \"name\": \"sv-SE-Wavenet" .
                "-E\",\r\n      \"language\": \"Swedish (Sweden)\",\r\n      \"gender\": \"MALE" .
                "\"\r\n    },\r\n    {\r\n      \"code\": \"ar-XA\",\r\n      \"name\": \"ar-XA-" .
                "Standard-D\",\r\n      \"language\": \"Arabic\",\r\n      \"gender\": \"FEMALE" .
                "\"\r\n    },\r\n    {\r\n      \"code\": \"fr-FR\",\r\n      \"name\": \"fr-FR-" .
                "Wavenet-A\",\r\n      \"language\": \"French (France)\",\r\n      \"gender\": " .
                "\"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"ar-XA\",\r\n      \"name\": " .
                "\"ar-XA-Wavenet-A\",\r\n      \"language\": \"Arabic\",\r\n      \"gender\": \"" .
                "FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"fr-FR\",\r\n      \"name\": \"" .
                "fr-FR-Wavenet-B\",\r\n      \"language\": \"French (France)\",\r\n      \"gende" .
                "r\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"ar-XA\",\r\n      \"name" .
                "\": \"ar-XA-Wavenet-B\",\r\n      \"language\": \"Arabic\",\r\n      \"gender\"" .
                ": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"ar-XA\",\r\n      \"name\": " .
                "\"ar-XA-Wavenet-C\",\r\n      \"language\": \"Arabic\",\r\n      \"gender\": \"" .
                "MALE\"\r\n    },\r\n    {\r\n      \"code\": \"ta-IN\",\r\n      \"name\": \"ta" .
                "-IN-Standard-A\",\r\n      \"language\": \"Tamil (India)\",\r\n      \"gender\"" .
                ": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"ar-XA\",\r\n      \"name\"" .
                ": \"ar-XA-Wavenet-D\",\r\n      \"language\": \"Arabic\",\r\n      \"gender\": " .
                "\"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"ta-IN\",\r\n      \"name\": " .
                "\"ta-IN-Standard-B\",\r\n      \"language\": \"Tamil (India)\",\r\n      \"gend" .
                "er\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"bn-IN\",\r\n      \"name" .
                "\": \"bn-IN-Standard-A\",\r\n      \"language\": \"Bengali (India)\",\r\n      " .
                "\"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"ta-IN\",\r\n    " .
                "  \"name\": \"ta-IN-Wavenet-A\",\r\n      \"language\": \"Tamil (India)\",\r\n " .
                "     \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"bn-IN\",\r" .
                "\n      \"name\": \"bn-IN-Standard-B\",\r\n      \"language\": \"Bengali (India" .
                ")\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"fr-F" .
                "R\",\r\n      \"name\": \"fr-FR-Wavenet-C\",\r\n      \"language\": \"French (F" .
                "rance)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\":" .
                " \"ta-IN\",\r\n      \"name\": \"ta-IN-Wavenet-B\",\r\n      \"language\": \"Ta" .
                "mil (India)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code" .
                "\": \"bn-IN\",\r\n      \"name\": \"bn-IN-Wavenet-A\",\r\n      \"language\": " .
                "\"Bengali (India)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n    " .
                "  \"code\": \"te-IN\",\r\n      \"name\": \"te-IN-Standard-A\",\r\n      \"lang" .
                "uage\": \"Telugu (India)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {" .
                "\r\n      \"code\": \"fr-FR\",\r\n      \"name\": \"fr-FR-Wavenet-D\",\r\n     " .
                " \"language\": \"French (France)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n" .
                "    {\r\n      \"code\": \"te-IN\",\r\n      \"name\": \"te-IN-Standard-B\",\r" .
                "\n      \"language\": \"Telugu (India)\",\r\n      \"gender\": \"MALE\"\r\n    " .
                "},\r\n    {\r\n      \"code\": \"bn-IN\",\r\n      \"name\": \"bn-IN-Wavenet-B" .
                "\",\r\n      \"language\": \"Bengali (India)\",\r\n      \"gender\": \"MALE\"\r" .
                "\n    },\r\n    {\r\n      \"code\": \"fr-FR\",\r\n      \"name\": \"fr-FR-Wave" .
                "net-E\",\r\n      \"language\": \"French (France)\",\r\n      \"gender\": \"FEM" .
                "ALE\"\r\n    },\r\n    {\r\n      \"code\": \"th-TH\",\r\n      \"name\": \"th-" .
                "TH-Standard-A\",\r\n      \"language\": \"Thai (Thailand)\",\r\n      \"gender" .
                "\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"bg-BG\",\r\n      \"name" .
                "\": \"bg-bg-Standard-A\",\r\n      \"language\": \"Bulgarian (Bulgaria)\",\r\n " .
                "     \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"de-DE\",\r" .
                "\n      \"name\": \"de-DE-Standard-A\",\r\n      \"language\": \"German (German" .
                "y)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"t" .
                "r-TR\",\r\n      \"name\": \"tr-TR-Standard-A\",\r\n      \"language\": \"Turki" .
                "sh (Turkey)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"co" .
                "de\": \"ca-ES\",\r\n      \"name\": \"ca-es-Standard-A\",\r\n      \"language\"" .
                ": \"Catalan (Spain)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n  " .
                "    \"code\": \"de-DE\",\r\n      \"name\": \"de-DE-Standard-B\",\r\n      \"la" .
                "nguage\": \"German (Germany)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    " .
                "{\r\n      \"code\": \"yue-HK\",\r\n      \"name\": \"yue-HK-Standard-A\",\r\n " .
                "     \"language\": \"Chinese (Hong Kong)\",\r\n      \"gender\": \"FEMALE\"\r\n" .
                "    },\r\n    {\r\n      \"code\": \"de-DE\",\r\n      \"name\": \"de-DE-Standa" .
                "rd-C\",\r\n      \"language\": \"German (Germany)\",\r\n      \"gender\": \"FEM" .
                "ALE\"\r\n    },\r\n    {\r\n      \"code\": \"yue-HK\",\r\n      \"name\": \"yu" .
                "e-HK-Standard-B\",\r\n      \"language\": \"Chinese (Hong Kong)\",\r\n      \"g" .
                "ender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"de-DE\",\r\n      \"n" .
                "ame\": \"de-DE-Standard-D\",\r\n      \"language\": \"German (Germany)\",\r\n  " .
                "    \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"yue-HK\",\r\n " .
                "     \"name\": \"yue-HK-Standard-C\",\r\n      \"language\": \"Chinese (Hong Ko" .
                "ng)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"" .
                "de-DE\",\r\n      \"name\": \"de-DE-Standard-E\",\r\n      \"language\": \"Germ" .
                "an (Germany)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"cod" .
                "e\": \"tr-TR\",\r\n      \"name\": \"tr-TR-Standard-B\",\r\n      \"language\":" .
                " \"Turkish (Turkey)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n    " .
                "  \"code\": \"de-DE\",\r\n      \"name\": \"de-DE-Standard-F\",\r\n      \"lang" .
                "uage\": \"German (Germany)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    " .
                "{\r\n      \"code\": \"tr-TR\",\r\n      \"name\": \"tr-TR-Standard-C\",\r\n   " .
                "   \"language\": \"Turkish (Turkey)\",\r\n      \"gender\": \"FEMALE\"\r\n    }" .
                ",\r\n    {\r\n      \"code\": \"tr-TR\",\r\n      \"name\": \"tr-TR-Standard-D" .
                "\",\r\n      \"language\": \"Turkish (Turkey)\",\r\n      \"gender\": \"FEMALE" .
                "\"\r\n    },\r\n    {\r\n      \"code\": \"yue-HK\",\r\n      \"name\": \"yue-H" .
                "K-Standard-D\",\r\n      \"language\": \"Chinese (Hong Kong)\",\r\n      \"gend" .
                "er\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"de-DE\",\r\n      \"name" .
                "\": \"de-DE-Wavenet-A\",\r\n      \"language\": \"German (Germany)\",\r\n      " .
                "\"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"tr-TR\",\r\n    " .
                "  \"name\": \"tr-TR-Standard-E\",\r\n      \"language\": \"Turkish (Turkey)\"," .
                "\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"cs-CZ\"," .
                "\r\n      \"name\": \"cs-CZ-Standard-A\",\r\n      \"language\": \"Czech (Czech" .
                " Republic)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"cod" .
                "e\": \"de-DE\",\r\n      \"name\": \"de-DE-Wavenet-B\",\r\n      \"language\": " .
                "\"German (Germany)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n     " .
                " \"code\": \"tr-TR\",\r\n      \"name\": \"tr-TR-Wavenet-A\",\r\n      \"langua" .
                "ge\": \"Turkish (Turkey)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {" .
                "\r\n      \"code\": \"de-DE\",\r\n      \"name\": \"de-DE-Wavenet-C\",\r\n     " .
                " \"language\": \"German (Germany)\",\r\n      \"gender\": \"FEMALE\"\r\n    }," .
                "\r\n    {\r\n      \"code\": \"tr-TR\",\r\n      \"name\": \"tr-TR-Wavenet-B\"," .
                "\r\n      \"language\": \"Turkish (Turkey)\",\r\n      \"gender\": \"MALE\"\r\n" .
                "    },\r\n    {\r\n      \"code\": \"cs-CZ\",\r\n      \"name\": \"cs-CZ-Wavene" .
                "t-A\",\r\n      \"language\": \"Czech (Czech Republic)\",\r\n      \"gender\": " .
                "\"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"de-DE\",\r\n      \"name\": " .
                "\"de-DE-Wavenet-D\",\r\n      \"language\": \"German (Germany)\",\r\n      \"ge" .
                "nder\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"da-DK\",\r\n      \"na" .
                "me\": \"da-DK-Standard-A\",\r\n      \"language\": \"Danish (Denmark)\",\r\n   " .
                "   \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"de-DE\",\r\n " .
                "     \"name\": \"de-DE-Wavenet-E\",\r\n      \"language\": \"German (Germany)\"" .
                ",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"da-DK\"" .
                ",\r\n      \"name\": \"da-DK-Standard-C\",\r\n      \"language\": \"Danish (Den" .
                "mark)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"" .
                "de-DE\",\r\n      \"name\": \"de-DE-Wavenet-F\",\r\n      \"language\": \"Germa" .
                "n (Germany)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"co" .
                "de\": \"da-DK\",\r\n      \"name\": \"da-DK-Standard-D\",\r\n      \"language\"" .
                ": \"Danish (Denmark)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n " .
                "     \"code\": \"el-GR\",\r\n      \"name\": \"el-GR-Standard-A\",\r\n      \"l" .
                "anguage\": \"Greek (Greece)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n   " .
                " {\r\n      \"code\": \"el-GR\",\r\n      \"name\": \"el-GR-Wavenet-A\",\r\n   " .
                "   \"language\": \"Greek (Greece)\",\r\n      \"gender\": \"FEMALE\"\r\n    }," .
                "\r\n    {\r\n      \"code\": \"tr-TR\",\r\n      \"name\": \"tr-TR-Wavenet-C\"," .
                "\r\n      \"language\": \"Turkish (Turkey)\",\r\n      \"gender\": \"FEMALE\"\r" .
                "\n    },\r\n    {\r\n      \"code\": \"gu-IN\",\r\n      \"name\": \"gu-IN-Stan" .
                "dard-A\",\r\n      \"language\": \"Gujarati (India)\",\r\n      \"gender\": \"F" .
                "EMALE\"\r\n    },\r\n    {\r\n      \"code\": \"tr-TR\",\r\n      \"name\": \"t" .
                "r-TR-Wavenet-D\",\r\n      \"language\": \"Turkish (Turkey)\",\r\n      \"gende" .
                "r\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"gu-IN\",\r\n      \"nam" .
                "e\": \"gu-IN-Standard-B\",\r\n      \"language\": \"Gujarati (India)\",\r\n    " .
                "  \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"gu-IN\",\r\n    " .
                "  \"name\": \"gu-IN-Wavenet-A\",\r\n      \"language\": \"Gujarati (India)\",\r" .
                "\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"tr-TR\"," .
                "\r\n      \"name\": \"tr-TR-Wavenet-E\",\r\n      \"language\": \"Turkish (Turk" .
                "ey)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"gu" .
                "-IN\",\r\n      \"name\": \"gu-IN-Wavenet-B\",\r\n      \"language\": \"Gujarat" .
                "i (India)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\"" .
                ": \"uk-UA\",\r\n      \"name\": \"uk-UA-Standard-A\",\r\n      \"language\": \"" .
                "Ukrainian (Ukraine)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n  " .
                "    \"code\": \"hi-IN\",\r\n      \"name\": \"hi-IN-Standard-A\",\r\n      \"la" .
                "nguage\": \"Hindi (India)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {" .
                "\r\n      \"code\": \"uk-UA\",\r\n      \"name\": \"uk-UA-Wavenet-A\",\r\n     " .
                " \"language\": \"Ukrainian (Ukraine)\",\r\n      \"gender\": \"FEMALE\"\r\n    " .
                "},\r\n    {\r\n      \"code\": \"hi-IN\",\r\n      \"name\": \"hi-IN-Standard-B" .
                "\",\r\n      \"language\": \"Hindi (India)\",\r\n      \"gender\": \"MALE\"\r\n" .
                "    },\r\n    {\r\n      \"code\": \"vi-VN\",\r\n      \"name\": \"vi-VN-Standa" .
                "rd-A\",\r\n      \"language\": \"Vietnamese (Vietnam)\",\r\n      \"gender\": " .
                "\"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"vi-VN\",\r\n      \"name\": " .
                "\"vi-VN-Standard-B\",\r\n      \"language\": \"Vietnamese (Vietnam)\",\r\n     " .
                " \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"hi-IN\",\r\n     " .
                " \"name\": \"hi-IN-Standard-C\",\r\n      \"language\": \"Hindi (India)\",\r\n " .
                "     \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"vi-VN\",\r\n " .
                "     \"name\": \"vi-VN-Standard-C\",\r\n      \"language\": \"Vietnamese (Vietn" .
                "am)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"" .
                "hi-IN\",\r\n      \"name\": \"hi-IN-Standard-D\",\r\n      \"language\": \"Hind" .
                "i (India)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code" .
                "\": \"da-DK\",\r\n      \"name\": \"da-DK-Standard-E\",\r\n      \"language\": " .
                "\"Danish (Denmark)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n   " .
                "   \"code\": \"hi-IN\",\r\n      \"name\": \"hi-IN-Wavenet-A\",\r\n      \"lang" .
                "uage\": \"Hindi (India)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r" .
                "\n      \"code\": \"da-DK\",\r\n      \"name\": \"da-DK-Wavenet-A\",\r\n      " .
                "\"language\": \"Danish (Denmark)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r" .
                "\n    {\r\n      \"code\": \"hi-IN\",\r\n      \"name\": \"hi-IN-Wavenet-B\",\r" .
                "\n      \"language\": \"Hindi (India)\",\r\n      \"gender\": \"MALE\"\r\n    }" .
                ",\r\n    {\r\n      \"code\": \"da-DK\",\r\n      \"name\": \"da-DK-Wavenet-C\"" .
                ",\r\n      \"language\": \"Danish (Denmark)\",\r\n      \"gender\": \"MALE\"\r" .
                "\n    },\r\n    {\r\n      \"code\": \"hi-IN\",\r\n      \"name\": \"hi-IN-Wave" .
                "net-C\",\r\n      \"language\": \"Hindi (India)\",\r\n      \"gender\": \"MALE" .
                "\"\r\n    },\r\n    {\r\n      \"code\": \"da-DK\",\r\n      \"name\": \"da-DK-" .
                "Wavenet-D\",\r\n      \"language\": \"Danish (Denmark)\",\r\n      \"gender\": " .
                "\"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"hi-IN\",\r\n      \"name\": " .
                "\"hi-IN-Wavenet-D\",\r\n      \"language\": \"Hindi (India)\",\r\n      \"gende" .
                "r\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"da-DK\",\r\n      \"nam" .
                "e\": \"da-DK-Wavenet-E\",\r\n      \"language\": \"Danish (Denmark)\",\r\n     " .
                " \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"hu-HU\",\r\n   " .
                "   \"name\": \"hu-HU-Standard-A\",\r\n      \"language\": \"Hungarian (Hungary)" .
                "\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"nl-" .
                "BE\",\r\n      \"name\": \"nl-BE-Standard-A\",\r\n      \"language\": \"Dutch (" .
                "Belgium)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code" .
                "\": \"hu-HU\",\r\n      \"name\": \"hu-HU-Wavenet-A\",\r\n      \"language\": " .
                "\"Hungarian (Hungary)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n" .
                "      \"code\": \"vi-VN\",\r\n      \"name\": \"vi-VN-Standard-D\",\r\n      \"" .
                "language\": \"Vietnamese (Vietnam)\",\r\n      \"gender\": \"MALE\"\r\n    },\r" .
                "\n    {\r\n      \"code\": \"nl-BE\",\r\n      \"name\": \"nl-BE-Standard-B\"," .
                "\r\n      \"language\": \"Dutch (Belgium)\",\r\n      \"gender\": \"MALE\"\r\n " .
                "   },\r\n    {\r\n      \"code\": \"is-IS\",\r\n      \"name\": \"is-is-Standar" .
                "d-A\",\r\n      \"language\": \"Icelandic (Iceland)\",\r\n      \"gender\": \"F" .
                "EMALE\"\r\n    },\r\n    {\r\n      \"code\": \"vi-VN\",\r\n      \"name\": \"v" .
                "i-VN-Wavenet-A\",\r\n      \"language\": \"Vietnamese (Vietnam)\",\r\n      \"g" .
                "ender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"nl-BE\",\r\n      " .
                "\"name\": \"nl-BE-Wavenet-A\",\r\n      \"language\": \"Dutch (Belgium)\",\r\n " .
                "     \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"id-ID\",\r" .
                "\n      \"name\": \"id-ID-Standard-A\",\r\n      \"language\": \"Indonesian (In" .
                "donesia)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code" .
                "\": \"vi-VN\",\r\n      \"name\": \"vi-VN-Wavenet-B\",\r\n      \"language\": " .
                "\"Vietnamese (Vietnam)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n " .
                "     \"code\": \"nl-BE\",\r\n      \"name\": \"nl-BE-Wavenet-B\",\r\n      \"la" .
                "nguage\": \"Dutch (Belgium)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {" .
                "\r\n      \"code\": \"id-ID\",\r\n      \"name\": \"id-ID-Standard-B\",\r\n    " .
                "  \"language\": \"Indonesian (Indonesia)\",\r\n      \"gender\": \"MALE\"\r\n  " .
                "  },\r\n    {\r\n      \"code\": \"nl-NL\",\r\n      \"name\": \"nl-NL-Standard" .
                "-A\",\r\n      \"language\": \"Dutch (Netherlands)\",\r\n      \"gender\": \"FE" .
                "MALE\"\r\n    },\r\n    {\r\n      \"code\": \"vi-VN\",\r\n      \"name\": \"vi" .
                "-VN-Wavenet-C\",\r\n      \"language\": \"Vietnamese (Vietnam)\",\r\n      \"ge" .
                "nder\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"id-ID\",\r\n      \"" .
                "name\": \"id-ID-Standard-C\",\r\n      \"language\": \"Indonesian (Indonesia)\"" .
                ",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"nl-NL\"" .
                ",\r\n      \"name\": \"nl-NL-Standard-B\",\r\n      \"language\": \"Dutch (Neth" .
                "erlands)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\":" .
                " \"id-ID\",\r\n      \"name\": \"id-ID-Standard-D\",\r\n      \"language\": \"I" .
                "ndonesian (Indonesia)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n" .
                "      \"code\": \"nl-NL\",\r\n      \"name\": \"nl-NL-Standard-C\",\r\n      \"" .
                "language\": \"Dutch (Netherlands)\",\r\n      \"gender\": \"MALE\"\r\n    },\r" .
                "\n    {\r\n      \"code\": \"id-ID\",\r\n      \"name\": \"id-ID-Wavenet-A\",\r" .
                "\n      \"language\": \"Indonesian (Indonesia)\",\r\n      \"gender\": \"FEMALE" .
                "\"\r\n    },\r\n    {\r\n      \"code\": \"nl-NL\",\r\n      \"name\": \"nl-NL-" .
                "Standard-D\",\r\n      \"language\": \"Dutch (Netherlands)\",\r\n      \"gender" .
                "\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"id-ID\",\r\n      \"name" .
                "\": \"id-ID-Wavenet-B\",\r\n      \"language\": \"Indonesian (Indonesia)\",\r\n" .
                "      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"nl-NL\",\r\n" .
                "      \"name\": \"nl-NL-Standard-E\",\r\n      \"language\": \"Dutch (Netherlan" .
                "ds)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"" .
                "nl-NL\",\r\n      \"name\": \"nl-NL-Wavenet-A\",\r\n      \"language\": \"Dutch" .
                " (Netherlands)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      " .
                "\"code\": \"id-ID\",\r\n      \"name\": \"id-ID-Wavenet-C\",\r\n      \"languag" .
                "e\": \"Indonesian (Indonesia)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n   " .
                " {\r\n      \"code\": \"vi-VN\",\r\n      \"name\": \"vi-VN-Wavenet-D\",\r\n   " .
                "   \"language\": \"Vietnamese (Vietnam)\",\r\n      \"gender\": \"MALE\"\r\n   " .
                " },\r\n    {\r\n      \"code\": \"nl-NL\",\r\n      \"name\": \"nl-NL-Wavenet-B" .
                "\",\r\n      \"language\": \"Dutch (Netherlands)\",\r\n      \"gender\": \"MALE" .
                "\"\r\n    },\r\n    {\r\n      \"code\": \"id-ID\",\r\n      \"name\": \"id-ID-" .
                "Wavenet-D\",\r\n      \"language\": \"Indonesian (Indonesia)\",\r\n      \"gend" .
                "er\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"nl-NL\",\r\n      \"na" .
                "me\": \"nl-NL-Wavenet-C\",\r\n      \"language\": \"Dutch (Netherlands)\",\r\n " .
                "     \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"it-IT\",\r\n " .
                "     \"name\": \"it-IT-Standard-A\",\r\n      \"language\": \"Italian (Italy)\"" .
                ",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"nl-NL" .
                "\",\r\n      \"name\": \"nl-NL-Wavenet-D\",\r\n      \"language\": \"Dutch (Net" .
                "herlands)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code" .
                "\": \"it-IT\",\r\n      \"name\": \"it-IT-Standard-B\",\r\n      \"language\": " .
                "\"Italian (Italy)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n    " .
                "  \"code\": \"nl-NL\",\r\n      \"name\": \"nl-NL-Wavenet-E\",\r\n      \"langu" .
                "age\": \"Dutch (Netherlands)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n  " .
                "  {\r\n      \"code\": \"it-IT\",\r\n      \"name\": \"it-IT-Standard-C\",\r\n " .
                "     \"language\": \"Italian (Italy)\",\r\n      \"gender\": \"MALE\"\r\n    }," .
                "\r\n    {\r\n      \"code\": \"en-AU\",\r\n      \"name\": \"en-AU-Standard-A\"" .
                ",\r\n      \"language\": \"English (Australia)\",\r\n      \"gender\": \"FEMALE" .
                "\"\r\n    },\r\n    {\r\n      \"code\": \"it-IT\",\r\n      \"name\": \"it-IT-" .
                "Standard-D\",\r\n      \"language\": \"Italian (Italy)\",\r\n      \"gender\": " .
                "\"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"en-AU\",\r\n      \"name\": \"" .
                "en-AU-Standard-B\",\r\n      \"language\": \"English (Australia)\",\r\n      \"" .
                "gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"it-IT\",\r\n      \"" .
                "name\": \"it-IT-Wavenet-A\",\r\n      \"language\": \"Italian (Italy)\",\r\n   " .
                "   \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"en-AU\",\r\n " .
                "     \"name\": \"en-AU-Standard-C\",\r\n      \"language\": \"English (Australi" .
                "a)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"e" .
                "n-AU\",\r\n      \"name\": \"en-AU-Standard-D\",\r\n      \"language\": \"Engli" .
                "sh (Australia)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"c" .
                "ode\": \"it-IT\",\r\n      \"name\": \"it-IT-Wavenet-B\",\r\n      \"language\"" .
                ": \"Italian (Italy)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n  " .
                "    \"code\": \"en-AU\",\r\n      \"name\": \"en-AU-Wavenet-A\",\r\n      \"lan" .
                "guage\": \"English (Australia)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n" .
                "    {\r\n      \"code\": \"it-IT\",\r\n      \"name\": \"it-IT-Wavenet-C\",\r\n" .
                "      \"language\": \"Italian (Italy)\",\r\n      \"gender\": \"MALE\"\r\n    }" .
                ",\r\n    {\r\n      \"code\": \"en-AU\",\r\n      \"name\": \"en-AU-Wavenet-B\"" .
                ",\r\n      \"language\": \"English (Australia)\",\r\n      \"gender\": \"MALE\"" .
                "\r\n    },\r\n    {\r\n      \"code\": \"it-IT\",\r\n      \"name\": \"it-IT-Wa" .
                "venet-D\",\r\n      \"language\": \"Italian (Italy)\",\r\n      \"gender\": \"M" .
                "ALE\"\r\n    },\r\n    {\r\n      \"code\": \"en-AU\",\r\n      \"name\": \"en-" .
                "AU-Wavenet-C\",\r\n      \"language\": \"English (Australia)\",\r\n      \"gend" .
                "er\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"ja-JP\",\r\n      \"na" .
                "me\": \"ja-JP-Standard-A\",\r\n      \"language\": \"Japanese (Japan)\",\r\n   " .
                "   \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"en-AU\",\r\n " .
                "     \"name\": \"en-AU-Wavenet-D\",\r\n      \"language\": \"English (Australia" .
                ")\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"ja-J" .
                "P\",\r\n      \"name\": \"ja-JP-Standard-B\",\r\n      \"language\": \"Japanese" .
                " (Japan)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code" .
                "\": \"en-IN\",\r\n      \"name\": \"en-IN-Standard-A\",\r\n      \"language\": " .
                "\"English (India)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n    " .
                "  \"code\": \"ja-JP\",\r\n      \"name\": \"ja-JP-Standard-C\",\r\n      \"lang" .
                "uage\": \"Japanese (Japan)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {" .
                "\r\n      \"code\": \"en-IN\",\r\n      \"name\": \"en-IN-Standard-B\",\r\n    " .
                "  \"language\": \"English (India)\",\r\n      \"gender\": \"MALE\"\r\n    },\r" .
                "\n    {\r\n      \"code\": \"ja-JP\",\r\n      \"name\": \"ja-JP-Standard-D\"," .
                "\r\n      \"language\": \"Japanese (Japan)\",\r\n      \"gender\": \"MALE\"\r\n" .
                "    },\r\n    {\r\n      \"code\": \"en-IN\",\r\n      \"name\": \"en-IN-Standa" .
                "rd-C\",\r\n      \"language\": \"English (India)\",\r\n      \"gender\": \"MALE" .
                "\"\r\n    },\r\n    {\r\n      \"code\": \"ja-JP\",\r\n      \"name\": \"ja-JP-" .
                "Wavenet-A\",\r\n      \"language\": \"Japanese (Japan)\",\r\n      \"gender\": " .
                "\"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"en-IN\",\r\n      \"name\": " .
                "\"en-IN-Standard-D\",\r\n      \"language\": \"English (India)\",\r\n      \"ge" .
                "nder\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"ja-JP\",\r\n      \"" .
                "name\": \"ja-JP-Wavenet-B\",\r\n      \"language\": \"Japanese (Japan)\",\r\n  " .
                "    \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"en-IN\",\r\n" .
                "      \"name\": \"en-IN-Wavenet-A\",\r\n      \"language\": \"English (India)\"" .
                ",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"ja-JP" .
                "\",\r\n      \"name\": \"ja-JP-Wavenet-C\",\r\n      \"language\": \"Japanese (" .
                "Japan)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": " .
                "\"en-IN\",\r\n      \"name\": \"en-IN-Wavenet-B\",\r\n      \"language\": \"Eng" .
                "lish (India)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"cod" .
                "e\": \"ja-JP\",\r\n      \"name\": \"ja-JP-Wavenet-D\",\r\n      \"language\": " .
                "\"Japanese (Japan)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n     " .
                " \"code\": \"en-IN\",\r\n      \"name\": \"en-IN-Wavenet-C\",\r\n      \"langua" .
                "ge\": \"English (India)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n" .
                "      \"code\": \"kn-IN\",\r\n      \"name\": \"kn-IN-Standard-A\",\r\n      \"" .
                "language\": \"Kannada (India)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n " .
                "   {\r\n      \"code\": \"en-IN\",\r\n      \"name\": \"en-IN-Wavenet-D\",\r\n " .
                "     \"language\": \"English (India)\",\r\n      \"gender\": \"FEMALE\"\r\n    " .
                "},\r\n    {\r\n      \"code\": \"kn-IN\",\r\n      \"name\": \"kn-IN-Standard-B" .
                "\",\r\n      \"language\": \"Kannada (India)\",\r\n      \"gender\": \"MALE\"\r" .
                "\n    },\r\n    {\r\n      \"code\": \"en-GB\",\r\n      \"name\": \"en-GB-Stan" .
                "dard-A\",\r\n      \"language\": \"English (UK)\",\r\n      \"gender\": \"FEMAL" .
                "E\"\r\n    },\r\n    {\r\n      \"code\": \"kn-IN\",\r\n      \"name\": \"kn-IN" .
                "-Wavenet-A\",\r\n      \"language\": \"Kannada (India)\",\r\n      \"gender\": " .
                "\"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"en-GB\",\r\n      \"name\": " .
                "\"en-GB-Standard-B\",\r\n      \"language\": \"English (UK)\",\r\n      \"gende" .
                "r\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"kn-IN\",\r\n      \"name" .
                "\": \"kn-IN-Wavenet-B\",\r\n      \"language\": \"Kannada (India)\",\r\n      " .
                "\"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"en-GB\",\r\n      " .
                "\"name\": \"en-GB-Standard-C\",\r\n      \"language\": \"English (UK)\",\r\n   " .
                "   \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"ko-KR\",\r\n " .
                "     \"name\": \"ko-KR-Standard-A\",\r\n      \"language\": \"Korean (South Kor" .
                "ea)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"" .
                "en-GB\",\r\n      \"name\": \"en-GB-Standard-D\",\r\n      \"language\": \"Engl" .
                "ish (UK)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\":" .
                " \"ko-KR\",\r\n      \"name\": \"ko-KR-Standard-B\",\r\n      \"language\": \"K" .
                "orean (South Korea)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n  " .
                "    \"code\": \"en-GB\",\r\n      \"name\": \"en-GB-Standard-F\",\r\n      \"la" .
                "nguage\": \"English (UK)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {" .
                "\r\n      \"code\": \"ko-KR\",\r\n      \"name\": \"ko-KR-Standard-C\",\r\n    " .
                "  \"language\": \"Korean (South Korea)\",\r\n      \"gender\": \"MALE\"\r\n    " .
                "},\r\n    {\r\n      \"code\": \"ko-KR\",\r\n      \"name\": \"ko-KR-Standard-D" .
                "\",\r\n      \"language\": \"Korean (South Korea)\",\r\n      \"gender\": \"MAL" .
                "E\"\r\n    },\r\n    {\r\n      \"code\": \"ko-KR\",\r\n      \"name\": \"ko-KR" .
                "-Wavenet-A\",\r\n      \"language\": \"Korean (South Korea)\",\r\n      \"gende" .
                "r\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"en-GB\",\r\n      \"nam" .
                "e\": \"en-GB-Wavenet-A\",\r\n      \"language\": \"English (UK)\",\r\n      \"g" .
                "ender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"ko-KR\",\r\n      " .
                "\"name\": \"ko-KR-Wavenet-B\",\r\n      \"language\": \"Korean (South Korea)\"," .
                "\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"en-GB" .
                "\",\r\n      \"name\": \"en-GB-Wavenet-B\",\r\n      \"language\": \"English (U" .
                "K)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"en-" .
                "GB\",\r\n      \"name\": \"en-GB-Wavenet-C\",\r\n      \"language\": \"English " .
                "(UK)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": " .
                "\"ko-KR\",\r\n      \"name\": \"ko-KR-Wavenet-C\",\r\n      \"language\": \"Kor" .
                "ean (South Korea)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      " .
                "\"code\": \"en-GB\",\r\n      \"name\": \"en-GB-Wavenet-D\",\r\n      \"languag" .
                "e\": \"English (UK)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n    " .
                "  \"code\": \"en-GB\",\r\n      \"name\": \"en-GB-Wavenet-F\",\r\n      \"langu" .
                "age\": \"English (UK)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n" .
                "      \"code\": \"ko-KR\",\r\n      \"name\": \"ko-KR-Wavenet-D\",\r\n      \"l" .
                "anguage\": \"Korean (South Korea)\",\r\n      \"gender\": \"MALE\"\r\n    },\r" .
                "\n    {\r\n      \"code\": \"en-US\",\r\n      \"name\": \"en-US-Standard-A\"," .
                "\r\n      \"language\": \"English (US)\",\r\n      \"gender\": \"MALE\"\r\n    " .
                "},\r\n    {\r\n      \"code\": \"lv-LV\",\r\n      \"name\": \"lv-lv-Standard-A" .
                "\",\r\n      \"language\": \"Latvian (Latvia)\",\r\n      \"gender\": \"MALE\"" .
                "\r\n    },\r\n    {\r\n      \"code\": \"en-US\",\r\n      \"name\": \"en-US-St" .
                "andard-B\",\r\n      \"language\": \"English (US)\",\r\n      \"gender\": \"MAL" .
                "E\"\r\n    },\r\n    {\r\n      \"code\": \"ms-MY\",\r\n      \"name\": \"ms-MY" .
                "-Standard-A\",\r\n      \"language\": \"Malay (Malaysia)\",\r\n      \"gender\"" .
                ": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"en-US\",\r\n      \"name\"" .
                ": \"en-US-Standard-C\",\r\n      \"language\": \"English (US)\",\r\n      \"gen" .
                "der\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"ms-MY\",\r\n      \"n" .
                "ame\": \"ms-MY-Standard-B\",\r\n      \"language\": \"Malay (Malaysia)\",\r\n  " .
                "    \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"en-US\",\r\n  " .
                "    \"name\": \"en-US-Standard-D\",\r\n      \"language\": \"English (US)\",\r" .
                "\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"ms-MY\",\r" .
                "\n      \"name\": \"ms-MY-Standard-C\",\r\n      \"language\": \"Malay (Malaysi" .
                "a)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"e" .
                "n-US\",\r\n      \"name\": \"en-US-Standard-E\",\r\n      \"language\": \"Engli" .
                "sh (US)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\"" .
                ": \"ms-MY\",\r\n      \"name\": \"ms-MY-Standard-D\",\r\n      \"language\": \"" .
                "Malay (Malaysia)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      " .
                "\"code\": \"en-US\",\r\n      \"name\": \"en-US-Standard-F\",\r\n      \"langua" .
                "ge\": \"English (US)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n " .
                "     \"code\": \"ms-MY\",\r\n      \"name\": \"ms-MY-Wavenet-A\",\r\n      \"la" .
                "nguage\": \"Malay (Malaysia)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n  " .
                "  {\r\n      \"code\": \"en-US\",\r\n      \"name\": \"en-US-Standard-G\",\r\n " .
                "     \"language\": \"English (US)\",\r\n      \"gender\": \"FEMALE\"\r\n    }," .
                "\r\n    {\r\n      \"code\": \"ms-MY\",\r\n      \"name\": \"ms-MY-Wavenet-B\"," .
                "\r\n      \"language\": \"Malay (Malaysia)\",\r\n      \"gender\": \"MALE\"\r\n" .
                "    },\r\n    {\r\n      \"code\": \"ms-MY\",\r\n      \"name\": \"ms-MY-Wavene" .
                "t-C\",\r\n      \"language\": \"Malay (Malaysia)\",\r\n      \"gender\": \"FEMA" .
                "LE\"\r\n    },\r\n    {\r\n      \"code\": \"ms-MY\",\r\n      \"name\": \"ms-M" .
                "Y-Wavenet-D\",\r\n      \"language\": \"Malay (Malaysia)\",\r\n      \"gender\"" .
                ": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"ml-IN\",\r\n      \"name\": " .
                "\"ml-IN-Standard-A\",\r\n      \"language\": \"Malayalam (India)\",\r\n      \"" .
                "gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"en-US\",\r\n      " .
                "\"name\": \"en-US-Standard-H\",\r\n      \"language\": \"English (US)\",\r\n   " .
                "   \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"ml-IN\",\r\n " .
                "     \"name\": \"ml-IN-Standard-B\",\r\n      \"language\": \"Malayalam (India)" .
                "\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"en-US" .
                "\",\r\n      \"name\": \"en-US-Standard-I\",\r\n      \"language\": \"English (" .
                "US)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"ml" .
                "-IN\",\r\n      \"name\": \"ml-IN-Wavenet-A\",\r\n      \"language\": \"Malayal" .
                "am (India)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"cod" .
                "e\": \"en-US\",\r\n      \"name\": \"en-US-Standard-J\",\r\n      \"language\":" .
                " \"English (US)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"" .
                "code\": \"en-US\",\r\n      \"name\": \"en-US-Wavenet-A\",\r\n      \"language" .
                "\": \"English (US)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n     " .
                " \"code\": \"ml-IN\",\r\n      \"name\": \"ml-IN-Wavenet-B\",\r\n      \"langua" .
                "ge\": \"Malayalam (India)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r" .
                "\n      \"code\": \"en-US\",\r\n      \"name\": \"en-US-Wavenet-B\",\r\n      " .
                "\"language\": \"English (US)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    " .
                "{\r\n      \"code\": \"cmn-CN\",\r\n      \"name\": \"cmn-CN-Standard-A\",\r\n " .
                "     \"language\": \"Mandarin Chinese\",\r\n      \"gender\": \"FEMALE\"\r\n   " .
                " },\r\n    {\r\n      \"code\": \"en-US\",\r\n      \"name\": \"en-US-Wavenet-C" .
                "\",\r\n      \"language\": \"English (US)\",\r\n      \"gender\": \"FEMALE\"\r" .
                "\n    },\r\n    {\r\n      \"code\": \"cmn-CN\",\r\n      \"name\": \"cmn-CN-St" .
                "andard-B\",\r\n      \"language\": \"Mandarin Chinese\",\r\n      \"gender\": " .
                "\"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"en-US\",\r\n      \"name\": \"" .
                "en-US-Wavenet-D\",\r\n      \"language\": \"English (US)\",\r\n      \"gender\"" .
                ": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"cmn-CN\",\r\n      \"name\":" .
                " \"cmn-CN-Standard-C\",\r\n      \"language\": \"Mandarin Chinese\",\r\n      " .
                "\"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"en-US\",\r\n      " .
                "\"name\": \"en-US-Wavenet-E\",\r\n      \"language\": \"English (US)\",\r\n    " .
                "  \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"cmn-CN\",\r\n " .
                "     \"name\": \"cmn-CN-Standard-D\",\r\n      \"language\": \"Mandarin Chinese" .
                "\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"en-" .
                "US\",\r\n      \"name\": \"en-US-Wavenet-F\",\r\n      \"language\": \"English " .
                "(US)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": " .
                "\"cmn-CN\",\r\n      \"name\": \"cmn-CN-Wavenet-A\",\r\n      \"language\": \"M" .
                "andarin Chinese\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      " .
                "\"code\": \"en-US\",\r\n      \"name\": \"en-US-Wavenet-G\",\r\n      \"languag" .
                "e\": \"English (US)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n  " .
                "    \"code\": \"cmn-CN\",\r\n      \"name\": \"cmn-CN-Wavenet-B\",\r\n      \"l" .
                "anguage\": \"Mandarin Chinese\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n   " .
                " {\r\n      \"code\": \"cmn-CN\",\r\n      \"name\": \"cmn-CN-Wavenet-C\",\r\n " .
                "     \"language\": \"Mandarin Chinese\",\r\n      \"gender\": \"MALE\"\r\n    }" .
                ",\r\n    {\r\n      \"code\": \"cmn-CN\",\r\n      \"name\": \"cmn-CN-Wavenet-D" .
                "\",\r\n      \"language\": \"Mandarin Chinese\",\r\n      \"gender\": \"FEMALE" .
                "\"\r\n    },\r\n    {\r\n      \"code\": \"en-US\",\r\n      \"name\": \"en-US-" .
                "Wavenet-H\",\r\n      \"language\": \"English (US)\",\r\n      \"gender\": \"FE" .
                "MALE\"\r\n    },\r\n    {\r\n      \"code\": \"cmn-TW\",\r\n      \"name\": \"c" .
                "mn-TW-Standard-A\",\r\n      \"language\": \"Mandarin Chinese\",\r\n      \"gen" .
                "der\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"en-US\",\r\n      \"n" .
                "ame\": \"en-US-Wavenet-I\",\r\n      \"language\": \"English (US)\",\r\n      " .
                "\"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"cmn-TW\",\r\n     " .
                " \"name\": \"cmn-TW-Standard-B\",\r\n      \"language\": \"Mandarin Chinese\"," .
                "\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"en-US\"," .
                "\r\n      \"name\": \"en-US-Wavenet-J\",\r\n      \"language\": \"English (US)" .
                "\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"cmn-T" .
                "W\",\r\n      \"name\": \"cmn-TW-Standard-C\",\r\n      \"language\": \"Mandari" .
                "n Chinese\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\"" .
                ": \"cmn-TW\",\r\n      \"name\": \"cmn-TW-Wavenet-A\",\r\n      \"language\": " .
                "\"Mandarin Chinese\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n   " .
                "   \"code\": \"fil-PH\",\r\n      \"name\": \"fil-PH-Standard-A\",\r\n      \"l" .
                "anguage\": \"Filipino (Philippines)\",\r\n      \"gender\": \"FEMALE\"\r\n    }" .
                ",\r\n    {\r\n      \"code\": \"cmn-TW\",\r\n      \"name\": \"cmn-TW-Wavenet-B" .
                "\",\r\n      \"language\": \"Mandarin Chinese\",\r\n      \"gender\": \"MALE\"" .
                "\r\n    },\r\n    {\r\n      \"code\": \"fil-PH\",\r\n      \"name\": \"fil-PH-" .
                "Standard-B\",\r\n      \"language\": \"Filipino (Philippines)\",\r\n      \"gen" .
                "der\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"cmn-TW\",\r\n      \"" .
                "name\": \"cmn-TW-Wavenet-C\",\r\n      \"language\": \"Mandarin Chinese\",\r\n " .
                "     \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"fil-PH\",\r\n" .
                "      \"name\": \"fil-PH-Standard-C\",\r\n      \"language\": \"Filipino (Phili" .
                "ppines)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": " .
                "\"nb-NO\",\r\n      \"name\": \"nb-NO-Standard-A\",\r\n      \"language\": \"No" .
                "rwegian (Norway)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n     " .
                " \"code\": \"fil-PH\",\r\n      \"name\": \"fil-PH-Standard-D\",\r\n      \"lan" .
                "guage\": \"Filipino (Philippines)\",\r\n      \"gender\": \"MALE\"\r\n    },\r" .
                "\n    {\r\n      \"code\": \"fil-PH\",\r\n      \"name\": \"fil-PH-Wavenet-A\"," .
                "\r\n      \"language\": \"Filipino (Philippines)\",\r\n      \"gender\": \"FEMA" .
                "LE\"\r\n    },\r\n    {\r\n      \"code\": \"nb-NO\",\r\n      \"name\": \"nb-N" .
                "O-Standard-B\",\r\n      \"language\": \"Norwegian (Norway)\",\r\n      \"gende" .
                "r\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"nb-NO\",\r\n      \"name" .
                "\": \"nb-NO-Standard-C\",\r\n      \"language\": \"Norwegian (Norway)\",\r\n   " .
                "   \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"nb-NO\",\r\n " .
                "     \"name\": \"nb-NO-Standard-D\",\r\n      \"language\": \"Norwegian (Norway" .
                ")\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"nb-N" .
                "O\",\r\n      \"name\": \"nb-NO-Wavenet-A\",\r\n      \"language\": \"Norwegian" .
                " (Norway)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code" .
                "\": \"nb-NO\",\r\n      \"name\": \"nb-NO-Wavenet-B\",\r\n      \"language\": " .
                "\"Norwegian (Norway)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n   " .
                "   \"code\": \"nb-NO\",\r\n      \"name\": \"nb-NO-Wavenet-C\",\r\n      \"lang" .
                "uage\": \"Norwegian (Norway)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n  " .
                "  {\r\n      \"code\": \"nb-NO\",\r\n      \"name\": \"nb-NO-Wavenet-D\",\r\n  " .
                "    \"language\": \"Norwegian (Norway)\",\r\n      \"gender\": \"MALE\"\r\n    " .
                "},\r\n    {\r\n      \"code\": \"nb-NO\",\r\n      \"name\": \"nb-no-Standard-E" .
                "\",\r\n      \"language\": \"Norwegian (Norway)\",\r\n      \"gender\": \"FEMAL" .
                "E\"\r\n    },\r\n    {\r\n      \"code\": \"nb-NO\",\r\n      \"name\": \"nb-no" .
                "-Standard-E\",\r\n      \"language\": \"Norwegian (Norway)\",\r\n      \"gender" .
                "\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"nb-NO\",\r\n      \"name" .
                "\": \"nb-no-Wavenet-E\",\r\n      \"language\": \"Norwegian (Norway)\",\r\n    " .
                "  \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"pl-PL\",\r\n  " .
                "    \"name\": \"pl-PL-Standard-A\",\r\n      \"language\": \"Polish (Poland)\"," .
                "\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"pl-PL" .
                "\",\r\n      \"name\": \"pl-PL-Standard-B\",\r\n      \"language\": \"Polish (P" .
                "oland)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": " .
                "\"pl-PL\",\r\n      \"name\": \"pl-PL-Standard-C\",\r\n      \"language\": \"Po" .
                "lish (Poland)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"co" .
                "de\": \"pl-PL\",\r\n      \"name\": \"pl-PL-Standard-D\",\r\n      \"language\"" .
                ": \"Polish (Poland)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n  " .
                "    \"code\": \"pl-PL\",\r\n      \"name\": \"pl-PL-Standard-E\",\r\n      \"la" .
                "nguage\": \"Polish (Poland)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n   " .
                " {\r\n      \"code\": \"pl-PL\",\r\n      \"name\": \"pl-PL-Wavenet-A\",\r\n   " .
                "   \"language\": \"Polish (Poland)\",\r\n      \"gender\": \"FEMALE\"\r\n    }," .
                "\r\n    {\r\n      \"code\": \"pl-PL\",\r\n      \"name\": \"pl-PL-Wavenet-B\"," .
                "\r\n      \"language\": \"Polish (Poland)\",\r\n      \"gender\": \"MALE\"\r\n " .
                "   },\r\n    {\r\n      \"code\": \"pl-PL\",\r\n      \"name\": \"pl-PL-Wavenet" .
                "-C\",\r\n      \"language\": \"Polish (Poland)\",\r\n      \"gender\": \"MALE\"" .
                "\r\n    },\r\n    {\r\n      \"code\": \"pl-PL\",\r\n      \"name\": \"pl-PL-Wa" .
                "venet-D\",\r\n      \"language\": \"Polish (Poland)\",\r\n      \"gender\": \"F" .
                "EMALE\"\r\n    },\r\n    {\r\n      \"code\": \"pl-PL\",\r\n      \"name\": \"p" .
                "l-PL-Wavenet-E\",\r\n      \"language\": \"Polish (Poland)\",\r\n      \"gender" .
                "\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"pt-BR\",\r\n      \"name" .
                "\": \"pt-BR-Standard-A\",\r\n      \"language\": \"Portuguese (Brazil)\",\r\n  " .
                "    \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"pt-BR\",\r\n" .
                "      \"name\": \"pt-BR-Standard-B\",\r\n      \"language\": \"Portuguese (Braz" .
                "il)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"pt" .
                "-BR\",\r\n      \"name\": \"pt-BR-Wavenet-A\",\r\n      \"language\": \"Portugu" .
                "ese (Brazil)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"c" .
                "ode\": \"pt-BR\",\r\n      \"name\": \"pt-BR-Wavenet-B\",\r\n      \"language\"" .
                ": \"Portuguese (Brazil)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n" .
                "      \"code\": \"pt-PT\",\r\n      \"name\": \"pt-PT-Standard-A\",\r\n      \"" .
                "language\": \"Portuguese (Portugal)\",\r\n      \"gender\": \"FEMALE\"\r\n    }" .
                ",\r\n    {\r\n      \"code\": \"pt-PT\",\r\n      \"name\": \"pt-PT-Standard-B" .
                "\",\r\n      \"language\": \"Portuguese (Portugal)\",\r\n      \"gender\": \"MA" .
                "LE\"\r\n    },\r\n    {\r\n      \"code\": \"pt-PT\",\r\n      \"name\": \"pt-P" .
                "T-Standard-C\",\r\n      \"language\": \"Portuguese (Portugal)\",\r\n      \"ge" .
                "nder\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"pt-PT\",\r\n      \"na" .
                "me\": \"pt-PT-Standard-D\",\r\n      \"language\": \"Portuguese (Portugal)\",\r" .
                "\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"pt-PT\"," .
                "\r\n      \"name\": \"pt-PT-Wavenet-A\",\r\n      \"language\": \"Portuguese (P" .
                "ortugal)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code" .
                "\": \"pt-PT\",\r\n      \"name\": \"pt-PT-Wavenet-B\",\r\n      \"language\": " .
                "\"Portuguese (Portugal)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n" .
                "      \"code\": \"pt-PT\",\r\n      \"name\": \"pt-PT-Wavenet-C\",\r\n      \"l" .
                "anguage\": \"Portuguese (Portugal)\",\r\n      \"gender\": \"MALE\"\r\n    },\r" .
                "\n    {\r\n      \"code\": \"pt-PT\",\r\n      \"name\": \"pt-PT-Wavenet-D\",\r" .
                "\n      \"language\": \"Portuguese (Portugal)\",\r\n      \"gender\": \"FEMALE" .
                "\"\r\n    },\r\n    {\r\n      \"code\": \"pa-IN\",\r\n      \"name\": \"pa-IN-" .
                "Standard-A\",\r\n      \"language\": \"Punjabi (India)\",\r\n      \"gender\": " .
                "\"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"pa-IN\",\r\n      \"name\": " .
                "\"pa-IN-Standard-B\",\r\n      \"language\": \"Punjabi (India)\",\r\n      \"ge" .
                "nder\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"pa-IN\",\r\n      \"na" .
                "me\": \"pa-IN-Standard-C\",\r\n      \"language\": \"Punjabi (India)\",\r\n    " .
                "  \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"pa-IN\",\r\n  " .
                "    \"name\": \"pa-IN-Standard-D\",\r\n      \"language\": \"Punjabi (India)\"," .
                "\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"pa-IN\"," .
                "\r\n      \"name\": \"pa-IN-Wavenet-A\",\r\n      \"language\": \"Punjabi (Indi" .
                "a)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"p" .
                "a-IN\",\r\n      \"name\": \"pa-IN-Wavenet-B\",\r\n      \"language\": \"Punjab" .
                "i (India)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\"" .
                ": \"pa-IN\",\r\n      \"name\": \"pa-IN-Wavenet-C\",\r\n      \"language\": \"P" .
                "unjabi (India)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      " .
                "\"code\": \"pa-IN\",\r\n      \"name\": \"pa-IN-Wavenet-D\",\r\n      \"languag" .
                "e\": \"Punjabi (India)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n " .
                "     \"code\": \"ro-RO\",\r\n      \"name\": \"ro-RO-Standard-A\",\r\n      \"l" .
                "anguage\": \"Romanian (Romania)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r" .
                "\n    {\r\n      \"code\": \"ro-RO\",\r\n      \"name\": \"ro-RO-Wavenet-A\",\r" .
                "\n      \"language\": \"Romanian (Romania)\",\r\n      \"gender\": \"FEMALE\"\r" .
                "\n    },\r\n    {\r\n      \"code\": \"ru-RU\",\r\n      \"name\": \"ru-RU-Stan" .
                "dard-A\",\r\n      \"language\": \"Russian (Russia)\",\r\n      \"gender\": \"F" .
                "EMALE\"\r\n    },\r\n    {\r\n      \"code\": \"ru-RU\",\r\n      \"name\": \"r" .
                "u-RU-Standard-B\",\r\n      \"language\": \"Russian (Russia)\",\r\n      \"gend" .
                "er\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"ru-RU\",\r\n      \"name" .
                "\": \"ru-RU-Standard-C\",\r\n      \"language\": \"Russian (Russia)\",\r\n     " .
                " \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"ru-RU\",\r\n   " .
                "   \"name\": \"ru-RU-Standard-D\",\r\n      \"language\": \"Russian (Russia)\"," .
                "\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"ru-RU\"," .
                "\r\n      \"name\": \"ru-RU-Standard-E\",\r\n      \"language\": \"Russian (Rus" .
                "sia)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": " .
                "\"ru-RU\",\r\n      \"name\": \"ru-RU-Wavenet-A\",\r\n      \"language\": \"Rus" .
                "sian (Russia)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"" .
                "code\": \"ru-RU\",\r\n      \"name\": \"ru-RU-Wavenet-B\",\r\n      \"language" .
                "\": \"Russian (Russia)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n " .
                "     \"code\": \"ru-RU\",\r\n      \"name\": \"ru-RU-Wavenet-C\",\r\n      \"la" .
                "nguage\": \"Russian (Russia)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n  " .
                "  {\r\n      \"code\": \"ru-RU\",\r\n      \"name\": \"ru-RU-Wavenet-D\",\r\n  " .
                "    \"language\": \"Russian (Russia)\",\r\n      \"gender\": \"MALE\"\r\n    }," .
                "\r\n    {\r\n      \"code\": \"ru-RU\",\r\n      \"name\": \"ru-RU-Wavenet-E\"," .
                "\r\n      \"language\": \"Russian (Russia)\",\r\n      \"gender\": \"FEMALE\"\r" .
                "\n    },\r\n    {\r\n      \"code\": \"sr-RS\",\r\n      \"name\": \"sr-rs-Stan" .
                "dard-A\",\r\n      \"language\": \"Serbian (Cyrillic)\",\r\n      \"gender\": " .
                "\"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"sk-SK\",\r\n      \"name\": " .
                "\"sk-SK-Standard-A\",\r\n      \"language\": \"Slovak (Slovakia)\",\r\n      \"" .
                "gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"sk-SK\",\r\n      " .
                "\"name\": \"sk-SK-Wavenet-A\",\r\n      \"language\": \"Slovak (Slovakia)\",\r" .
                "\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"es-ES\"," .
                "\r\n      \"name\": \"es-ES-Standard-A\",\r\n      \"language\": \"Spanish (Spa" .
                "in)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"" .
                "es-ES\",\r\n      \"name\": \"es-ES-Standard-B\",\r\n      \"language\": \"Span" .
                "ish (Spain)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code" .
                "\": \"es-ES\",\r\n      \"name\": \"es-ES-Standard-C\",\r\n      \"language\": " .
                "\"Spanish (Spain)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n    " .
                "  \"code\": \"es-ES\",\r\n      \"name\": \"es-ES-Standard-D\",\r\n      \"lang" .
                "uage\": \"Spanish (Spain)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {" .
                "\r\n      \"code\": \"es-ES\",\r\n      \"name\": \"es-ES-Wavenet-B\",\r\n     " .
                " \"language\": \"Spanish (Spain)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n" .
                "    {\r\n      \"code\": \"es-ES\",\r\n      \"name\": \"es-ES-Wavenet-C\",\r\n" .
                "      \"language\": \"Spanish (Spain)\",\r\n      \"gender\": \"FEMALE\"\r\n   " .
                " },\r\n    {\r\n      \"code\": \"es-ES\",\r\n      \"name\": \"es-ES-Wavenet-D" .
                "\",\r\n      \"language\": \"Spanish (Spain)\",\r\n      \"gender\": \"FEMALE\"" .
                "\r\n    },\r\n    {\r\n      \"code\": \"es-US\",\r\n      \"name\": \"es-US-St" .
                "andard-A\",\r\n      \"language\": \"Spanish (US)\",\r\n      \"gender\": \"FEM" .
                "ALE\"\r\n    },\r\n    {\r\n      \"code\": \"es-US\",\r\n      \"name\": \"es-" .
                "US-Standard-B\",\r\n      \"language\": \"Spanish (US)\",\r\n      \"gender\": " .
                "\"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"es-US\",\r\n      \"name\": \"" .
                "es-US-Standard-C\",\r\n      \"language\": \"Spanish (US)\",\r\n      \"gender" .
                "\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"es-US\",\r\n      \"name\"" .
                ": \"es-US-Wavenet-A\",\r\n      \"language\": \"Spanish (US)\",\r\n      \"gend" .
                "er\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"es-US\",\r\n      \"na" .
                "me\": \"es-US-Wavenet-B\",\r\n      \"language\": \"Spanish (US)\",\r\n      \"" .
                "gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"es-US\",\r\n      \"" .
                "name\": \"es-US-Wavenet-C\",\r\n      \"language\": \"Spanish (US)\",\r\n      " .
                "\"gender\": \"MALE\"\r\n    },\r\n    {\r\n      \"code\": \"sv-SE\",\r\n      " .
                "\"name\": \"sv-SE-Standard-A\",\r\n      \"language\": \"Swedish (Sweden)\",\r" .
                "\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": \"sv-SE\"," .
                "\r\n      \"name\": \"sv-SE-Standard-B\",\r\n      \"language\": \"Swedish (Swe" .
                "den)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      \"code\": " .
                "\"sv-SE\",\r\n      \"name\": \"sv-SE-Standard-C\",\r\n      \"language\": \"Sw" .
                "edish (Sweden)\",\r\n      \"gender\": \"FEMALE\"\r\n    },\r\n    {\r\n      " .
                "\"code\": \"sv-SE\",\r\n      \"name\": \"sv-SE-Standard-D\",\r\n      \"langua" .
                "ge\": \"Swedish (Sweden)\",\r\n      \"gender\": \"MALE\"\r\n    },\r\n    {\r" .
                "\n      \"code\": \"sv-SE\",\r\n      \"name\": \"sv-SE-Standard-E\",\r\n      " .
                "\"language\": \"Swedish (Sweden)\",\r\n      \"gender\": \"MALE\"\r\n    }\r\n " .
                " ]\r\n}"
            ),
            false,
            false
        ))
        ->assert();
    }
}
